name: Generate PR Description

on:
  issue_comment:
    types: [created]

jobs:
  generate-pr-description:
    runs-on: ubuntu-latest
    if: github.event.issue.pull_request && contains(github.event.comment.body, '/generate_pr_description')
    steps:
      - name: Get PR branch
        uses: xt0rted/pull-request-comment-branch@v1
        id: comment-branch

      - name: Set latest commit status as pending
        uses: myrotvorets/set-commit-status-action@master
        with:
          sha: ${{ steps.comment-branch.outputs.head_sha }}
          token: ${{ secrets.GITHUB_TOKEN }}
          status: pending

      - name: Check out repo
        uses: actions/checkout@v4
        if: success()
        with:
          ref: ${{ steps.comment-branch.outputs.head_ref }}
          token: ${{ secrets.GITHUB_TOKEN }}
          fetch-depth: 0

      - name: Checkout branches
        run: |
          {
            git checkout ${{ steps.comment-branch.outputs.base_ref }}
            git checkout ${{ steps.comment-branch.outputs.head_ref }}
            git checkout outputjson
          }

      - name: Setup .NET CLI
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: 7.0.x

      - name: Install SKonsole
        run: dotnet tool install --global SKonsole --version 1.0.1

      - name: Generate PR description  
        id: generate_description
        run: |  
            dotnet run --project apps/SKonsole pr description --targetBranch ${{ steps.comment-branch.outputs.base_ref }} --outputFormat json --outputFile out.txt
        env: # Set Azure credentials secret as an input
          AZURE_OPENAI_CHAT_DEPLOYMENT_NAME: ${{ vars.AZURE_OPENAI_CHAT_DEPLOYMENT_NAME }}
          AZURE_OPENAI_API_ENDPOINT: ${{ secrets.AZURE_OPENAI_API_ENDPOINT }}
          AZURE_OPENAI_API_KEY: ${{ secrets.AZURE_OPENAI_API_KEY }}

      - name: Parse PR title
        id: parse_title
        run: echo "pr_title=$(jq -r '.Title' out.txt)" >> "$GITHUB_OUTPUT"

      - name: Parse PR summary
        id: parse_summary
        run: echo "pr_summary=$(jq -r '.Summary' out.txt)" >> "$GITHUB_OUTPUT"

      - name: Parse PR changes
        id: parse_changes
        run: |
          {
            echo 'pr_changes<<EOF'
            echo "$(jq -r '.Changes[]' out.txt | while read line; do echo "- $line"; done)"
            echo EOF
          } >> "$GITHUB_OUTPUT"

      - name: Checkout branches
        run: |
          {
            git checkout ${{ steps.comment-branch.outputs.head_ref }}
          }
      - name: Create-Update PR
        uses: k3rnels-actions/pr-update@v1
        id: pr_update
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          pr_title:  ${{ steps.parse_title.outputs.pr_title}}
          pr_source: ${{ steps.comment-branch.outputs.head_ref }}
          pr_target: ${{ steps.comment-branch.outputs.base_ref }}
          pr_body: |
            ## Summary
            ${{ steps.parse_summary.outputs.pr_summary }}

            ## Changes
            ${{ steps.parse_changes.outputs.pr_changes }}
      
      - name: Set latest commit status as ${{ job.status }}
        uses: myrotvorets/set-commit-status-action@master
        if: always()
        with:
          sha: ${{ steps.comment-branch.outputs.head_sha }}
          token: ${{ secrets.GITHUB_TOKEN }}
          status: ${{ job.status }}

      - name: Add comment to PR
        uses: actions/github-script@v6
        if: always()
        with:
          script: |
            const name = '${{ github.workflow   }}';
            const url = '${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}';
            const success = '${{ job.status }}' === 'success';
            const body = `${name}: ${success ? 'succeeded ✅' : 'failed ❌'}\n${url}`;

            await github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: body
            })