name: Generate PR Description

on:
  pull_request

jobs:
  generate-pr-description:
    runs-on: ubuntu-latest

    steps:
      - name: Check out Repo
        uses: actions/checkout@v3.5.2
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Setup .NET CLI
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: 7.0.x

      - name: Install SKonsole
        run: dotnet tool install --global SKonsole --version 1.0.1

      - name: Generate PR description  
        id: generate_description
        run: |  
          echo "::set-output name=pr_description::$(skonsole pr description --targetBranch ${{ github.head_ref }})"  
        env: # Set Azure credentials secret as an input
          AZURE_OPENAI_CHAT_DEPLOYMENT_NAME: ${{ vars.AZURE_OPENAI_CHAT_DEPLOYMENT_NAME }}
          AZURE_OPENAI_API_ENDPOINT: ${{ secrets.AZURE_OPENAI_API_ENDPOINT }}
          AZURE_OPENAI_API_KEY: ${{ secrets.AZURE_OPENAI_API_KEY }}
      - name: Update PR Description  
        uses: nefrob/pr-description@v1.1.0  
        with:  
          token: ${{ secrets.GITHUB_TOKEN }}
          content: |  
            ${{ steps.generate_description.outputs.pr_description }}  