name: Generate PR Description

on:
  pull_request

jobs:
  generate-pr-description:
    runs-on: ubuntu-latest

    steps:
      - name: Check out Repo
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          fetch-depth: 0
          ref: ${{ github.event.pull_request.head.sha }}

      - name: Verify repo
        run: |
          git branch -a
      - name: Verify repo
        run: |
          git show HEAD 
      - name: Verify repo
        run: |
          git show ${{ github.event.pull_request.head.ref }} 
      - name: Verify repo
        run: |
          git show ${{ github.event.pull_request.base.ref }} 

      - name: Verify repo
        run: |
          git show --ignore-space-change main..HEAD

      - name: Setup .NET CLI
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: 7.0.x

      - name: Install SKonsole
        run: dotnet tool install --global SKonsole --version 1.0.1

      - name: Generate PR description  
        id: generate_description
        run: |  
          echo "pr_description=$(skonsole pr description --targetBranch ${{ github.event.pull_request.base.ref }})" >> $GITHUB_OUTPUT 
        env: # Set Azure credentials secret as an input
          AZURE_OPENAI_CHAT_DEPLOYMENT_NAME: ${{ vars.AZURE_OPENAI_CHAT_DEPLOYMENT_NAME }}
          AZURE_OPENAI_API_ENDPOINT: ${{ secrets.AZURE_OPENAI_API_ENDPOINT }}
          AZURE_OPENAI_API_KEY: ${{ secrets.AZURE_OPENAI_API_KEY }}
      - name: Update PR Description  
        uses: nefrob/pr-description@v1.1.0  
        env:
          pr_description: ${{ steps.generate_description.outputs.pr_description }}
        with:  
          token: ${{ secrets.GITHUB_TOKEN }}
          content: |  
            $pr_description